#!/usr/bin/env php
<?php

use Okay\Core\Console\Application;
use Okay\Core\ServiceLocator;

require __DIR__.'/vendor/autoload.php';

$serviceLocator = ServiceLocator::getInstance();

/** @var Application $app */
$app = $serviceLocator->getService(Application::class);

$app->run();