ALTER TABLE `ok_settings` ADD UNIQUE `param` (`param`);

INSERT INTO `ok_settings` (`param`, `value`) VALUES
('site_favicon', 'favicon.png'),
('site_favicon_version', '001'),
('site_logo_version', '001'),
('multilang_logo',	'0'),
('social_share_theme',	'flat'),
('sj_shares',	'a:4:{i:0;s:7:\"twitter\";i:1;s:8:\"facebook\";i:2;s:9:\"vkontakte\";i:3;s:13:\"odnoklassniki\";}'),
('recaptcha_scores',	'a:3:{s:7:\"product\";d:0.5;s:4:\"cart\";d:0.69999999999999996;s:5:\"other\";d:0.20000000000000001;}');

INSERT INTO `ok_settings_lang` (`param`, `lang_id`, `value`) VALUES
('site_working_hours',	1,	'<p><span class=\"times_text\" style=\"box-sizing: inherit; font-family: \'Open Sans\', sans-serif;\" data-language=\"index_we_open\">Режим работы магазина:</span><br /><span style=\"font-family: \'Open Sans\', sans-serif;\"><strong><span style=\"box-sizing: inherit;\" data-language=\"company_open_hours\">ПН - ПТ: с 9:00 до 18:00</span></strong></span></p>'),
('site_working_hours',	2,	'<p><span class=\"times_text\" style=\"box-sizing: inherit; color: #686666; font-family: \'Open Sans\', sans-serif;\" data-language=\"index_we_open\">Working hours:</span><br /><span style=\"color: #030303; font-family: \'Open Sans\', sans-serif; font-weight: bold;\">Mon-Fri: 9 a.m.- 6 p.m.</span></p>'),
('site_working_hours',	3,	'<p><span class=\"times_text\" style=\"box-sizing: inherit; color: #686666; font-family: \'Open Sans\', sans-serif;\" data-language=\"index_we_open\">Режим роботи магазину:</span><br /><span style=\"color: #030303; font-family: \'Open Sans\', sans-serif; font-weight: bold;\">ПН - ПТ: з 9:00 до 18:00</span></p>'),
('product_deliveries',	1,	'<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_delivery_1\">Новая Почта</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_delivery_2\">Другие транспортные службы</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_delivery_3\">Курьером по Киеву</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_delivery_4\">Самовывоз</p>'),
('product_payments',	1,	'<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_payment_1\">Наличными при получении</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_payment_2\">Безналичный перевод</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_payment_3\">Приват 24</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_payment_4\">WebMoney</p>'),
('product_deliveries',	2,	'<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_delivery_1\">New Post</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_delivery_2\">Other transport services</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_delivery_3\">Courier in Kiev</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_delivery_4\">Pickup</p>'),
('product_payments',	2,	'<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_payment_1\">Cash</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_payment_2\">Non-cash transfer</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_payment_3\">Privat 24</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_payment_4\">WebMoney</p>'),
('product_deliveries',	3,	'<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_delivery_1\">Нова Пошта</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_delivery_2\">Інші транспортні служби</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_delivery_3\">Кур\'єром по Києву</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_delivery_4\">Самовивезення</p>'),
('product_payments',	3,	'<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_payment_1\">Готівкою при отриманні</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_payment_2\">Безготівковий переказ</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_payment_3\">Приват 24</p>\r\n<p style=\"box-sizing: inherit; margin-top: 0px; margin-bottom: 7px; opacity: 0.7; color: #030303; font-family: \'Open Sans\', sans-serif;\" data-language=\"product_payment_4\">WebMoney</p>');

ALTER TABLE `ok_orders_status` ADD `status_1c` enum('new','accepted','to_delete', 'not_use') NULL DEFAULT 'not_use';

DELETE FROM `ok_settings` WHERE `param` = 'js_version';
DELETE FROM `ok_settings` WHERE `param` = 'css_version';
