INSERT INTO `ok_settings` (`param`, `value`) VALUES ('email_for_module', '');
ALTER TABLE `ok_categories`  ADD `on_main` INT(2) NOT NULL DEFAULT '0'  AFTER `visible`;
INSERT INTO `ok_settings` (`param`, `value`) VALUES
 ('open_ai_temperature', '1'),
 ('open_ai_presence_penalty', '0'),
 ('open_ai_frequency_penalty', '0'),
 ('open_ai_max_tokens', '4096');

INSERT INTO `ok_settings_lang` (`lang_id`, `param`, `value`) VALUES
 (3, 'ai_system_message', 'Ти редактор контенту для інтернет-магазину. Пиши зрозумілі SEO-тексти, використовуючи лише факти з назви та наданих характеристик. Не вигадуй технічні деталі. Не використовуй emoji. Повертай лише потрібний текст без вступу.'),
 (2, 'ai_system_message', 'You are an e-commerce content editor. Write clear SEO-friendly copy using only facts from the name and provided specifications. Never invent technical details. Do not use emoji. Return only the requested text without preamble.'),
 (1, 'ai_system_message', 'Ты редактор контента для интернет-магазина. Пиши понятные SEO-тексты, используя только факты из названия и предоставленных характеристик. Не выдумывай технические детали. Не используй emoji. Возвращай только нужный текст без вступления.'),
 (3, 'ai_product_title_template', 'Створи стислий SEO meta title для товару {$product}. Один рядок, без HTML, без крапки в кінці.'),
 (2, 'ai_product_title_template', 'Create a concise SEO meta title for the product {$product}. One line, no HTML, no trailing period.'),
 (1, 'ai_product_title_template', 'Создай краткий SEO meta title для товара {$product}. Одна строка, без HTML, без точки в конце.'),
 (3, 'ai_product_meta_description_template', 'Створи SEO meta description для товару {$product}. 1-2 речення, звичайний текст, за можливості вкажи конкретний факт.'),
 (2, 'ai_product_meta_description_template', 'Create an SEO meta description for the product {$product}. 1-2 sentences, plain text, include a concrete fact when available.'),
 (1, 'ai_product_meta_description_template', 'Создай SEO meta description для товара {$product}. 1-2 предложения, обычный текст, по возможности укажи конкретный факт.'),
 (3, 'ai_product_keywords_template', 'Напиши SEO-ключові слова для товару {$product} через кому. Без дублів.'),
 (2, 'ai_product_keywords_template', 'Write comma-separated SEO keywords for the product {$product}. No duplicates.'),
 (1, 'ai_product_keywords_template', 'Напиши SEO-ключевые слова для товара {$product} через запятую. Без дублей.'),
 (3, 'ai_product_description_template', 'Створи повний HTML-опис товару {$product}. Використовуй абзаци та списки. Пиши лише за наданими фактами.'),
 (2, 'ai_product_description_template', 'Create a full HTML product description for {$product}. Use paragraphs and bullet lists. Use only provided facts.'),
 (1, 'ai_product_description_template', 'Создай полное HTML-описание товара {$product}. Используй абзацы и списки. Пиши только по предоставленным фактам.'),
 (3, 'ai_product_annotation_template', 'Створи короткий опис товару {$product}. 2-3 речення.'),
 (2, 'ai_product_annotation_template', 'Create a short product summary for {$product}. 2-3 sentences.'),
 (1, 'ai_product_annotation_template', 'Создай краткое описание товара {$product}. 2-3 предложения.'),
 (3, 'ai_category_title_template', 'Створи стислий SEO meta title для категорії {$category}. Один рядок, без HTML, без крапки в кінці.'),
 (2, 'ai_category_title_template', 'Create a concise SEO meta title for the category {$category}. One line, no HTML, no trailing period.'),
 (1, 'ai_category_title_template', 'Создай краткий SEO meta title для категории {$category}. Одна строка, без HTML, без точки в конце.'),
 (3, 'ai_category_meta_description_template', 'Створи SEO meta description для категорії {$category}. 1-2 речення, звичайний текст.'),
 (2, 'ai_category_meta_description_template', 'Create an SEO meta description for the category {$category}. 1-2 sentences, plain text.'),
 (1, 'ai_category_meta_description_template', 'Создай SEO meta description для категории {$category}. 1-2 предложения, обычный текст.'),
 (3, 'ai_category_keywords_template', 'Напиши SEO-ключові слова для категорії {$category} через кому. Без дублів.'),
 (2, 'ai_category_keywords_template', 'Write comma-separated SEO keywords for the category {$category}. No duplicates.'),
 (1, 'ai_category_keywords_template', 'Напиши SEO-ключевые слова для категории {$category} через запятую. Без дублей.'),
 (3, 'ai_category_description_template', 'Створи повний HTML-опис категорії {$category}. Використовуй абзаци та списки. Пиши лише за наданими фактами.'),
 (2, 'ai_category_description_template', 'Create a full HTML category description for {$category}. Use paragraphs and bullet lists. Use only provided facts.'),
 (1, 'ai_category_description_template', 'Создай полное HTML-описание категории {$category}. Используй абзацы и списки. Пиши только по предоставленным фактам.'),
 (3, 'ai_category_annotation_template', 'Створи короткий опис категорії {$category}. 2-3 речення.'),
 (2, 'ai_category_annotation_template', 'Create a short category summary for {$category}. 2-3 sentences.'),
 (1, 'ai_category_annotation_template', 'Создай краткое описание категории {$category}. 2-3 предложения.'),
 (3, 'ai_brand_title_template', 'Створи стислий SEO meta title для бренда {$brand}. Один рядок, без HTML, без крапки в кінці.'),
 (2, 'ai_brand_title_template', 'Create a concise SEO meta title for the brand {$brand}. One line, no HTML, no trailing period.'),
 (1, 'ai_brand_title_template', 'Создай краткий SEO meta title для бренда {$brand}. Одна строка, без HTML, без точки в конце.'),
 (3, 'ai_brand_meta_description_template', 'Створи SEO meta description для бренда {$brand}. 1-2 речення, звичайний текст.'),
 (2, 'ai_brand_meta_description_template', 'Create an SEO meta description for the brand {$brand}. 1-2 sentences, plain text.'),
 (1, 'ai_brand_meta_description_template', 'Создай SEO meta description для бренда {$brand}. 1-2 предложения, обычный текст.'),
 (3, 'ai_brand_keywords_template', 'Напиши SEO-ключові слова для бренда {$brand} через кому. Без дублів.'),
 (2, 'ai_brand_keywords_template', 'Write comma-separated SEO keywords for the brand {$brand}. No duplicates.'),
 (1, 'ai_brand_keywords_template', 'Напиши SEO-ключевые слова для бренда {$brand} через запятую. Без дублей.'),
 (3, 'ai_brand_description_template', 'Створи повний HTML-опис бренда {$brand}. Використовуй абзаци та списки. Пиши лише за наданими фактами.'),
 (2, 'ai_brand_description_template', 'Create a full HTML brand description for {$brand}. Use paragraphs and bullet lists. Use only provided facts.'),
 (1, 'ai_brand_description_template', 'Создай полное HTML-описание бренда {$brand}. Используй абзацы и списки. Пиши только по предоставленным фактам.'),
 (3, 'ai_brand_annotation_template', 'Створи короткий опис бренда {$brand}. 2-3 речення.'),
 (2, 'ai_brand_annotation_template', 'Create a short brand summary for {$brand}. 2-3 sentences.'),
 (1, 'ai_brand_annotation_template', 'Создай краткое описание бренда {$brand}. 2-3 предложения.');




